import { sidebar } from "vuepress-theme-hope";

export const zhSidebar = sidebar({
  "/": [
    {
      icon: "semantic",
      text: "参数类",
      prefix: "operands/130/",
      link: "operands/130/",
      collapsible: true,
      children: [
        "870",
        "871",
        "872",
        "873",
        "874",
        "875",
        "876",
        "877",
        "878",
      ],
    },
    {
      icon: "engine",
      text: "分析属性类",
      prefix: "operands/131/",
      link: "operands/131/",
      collapsible: true,
      children: [
        "879",
        "880",
        "881",
        "882",
        "883",
        "884",
        "885",
        "886",
        "887",
        "888",
        "890",
        "891",
      ],
    },
    {
      icon: "float",
      text: "专有计算类",
      prefix: "operands/135/",
      link: "operands/135/",
      collapsible: true,
      children: [
        "892",
        "893",
        "894",
        "895",
        "896",
        "897",
        "898",
      ],
    },
    {
      icon: "mesh",
      text: "其他类",
      prefix: "operands/136/",
      link: "operands/136/",
      collapsible: true,
      children: [
        "899",
        "900",
        "901",
        "902",
        "903",
      ],
    },
  ],
});
